{{- if .Values.fusion.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "olake.fullname" . }}-fusion
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
type: Opaque
data:
  AdminUsername: {{ .Values.fusion.adminUser | b64enc | quote | default "admin" }}
  AdminPassword: {{ .Values.fusion.adminPassword | b64enc | quote | default "password" }}
  #TODO: need to import default from postgres secret
  DatabaseUsername: {{  .Values.fusion.database.username | b64enc | quote | default .Values.postgresql.auth.postgresUser}}
  DatabasePassword: {{  .Values.fusion.database.password | b64enc | quote | default .Values.postgresql.auth.postgresPassword}}
{{- end }}
