{{- if .Values.fusion.optimizer.spark.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fusion.optimizer.spark.serviceAccount.name | default "spark" }}
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
  {{- with .Values.fusion.optimizer.spark.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}