{{- if and .Values.fusion.enabled .Values.fusion.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "olake.fullname" . }}-fusion
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: fusion
spec:
  type: {{ .Values.fusion.ui.service.type | default "ClusterIP" }}
  {{- with .Values.fusion.ui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: rest
      port: {{ .Values.fusion.server.rest.port }}
      targetPort: {{ .Values.fusion.server.rest.port }}
      protocol: TCP
      {{- if .Values.fusion.ui.service.nodePort }}
      nodePort: {{ .Values.fusion.ui.service.nodePort }}
      {{- end }}
    - name: table
      port: {{ .Values.fusion.server.table.port }}
      targetPort: {{ .Values.fusion.server.table.port }}
      protocol: TCP
    - name: optimizing
      port: {{ .Values.fusion.server.optimizing.port }}
      targetPort: {{ .Values.fusion.server.optimizing.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "olake.name" . }}-fusion
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
